### ISSUE TITLE
"-E option not yet supported" + stub_msg

### ISSUE THREAD

**Issue by sm0ketst** [peteasa/parallella-yoctobuild#3]
Hi!

What am I doing bad?

```
sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm
git clone git@github.com:peteasa/parallella-yoctobuild
cd parallella-yoctobuild
source initgitsubmodules.sh
source prepareyoctobuild.sh
bitbake hdmi-image
```

[log.do_compile.30702.txt](https://github.com/peteasa/parallella-yoctobuild/files/230235/log.do_compile.30702.txt)

```
Traceback (most recent call last):
  File "/media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella/parallella-yoctobuild/build_parallella/tmp/sysroots/x86_64-linux/usr/bin/texinfo-dummy-native/makeinfo", line 109, in <module>
    "-E option not yet supported" + stub_msg
AssertionError: -E option not yet supported
This stand-in version of makeinfo is not yet fully capable of emulating the real
version from the GNU texinfo suite. If you see this message, file a bug report
with details on the recipe that failed.
```

```
sm0ketst@neonbox:/media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella/parallella-yoctobuild/build_parallella$ uname -a
Linux neonbox 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
```

TIA

JJ

**Comment by peteasa** [comment]
Thanks for having a go with Yocto.  I am not sure about your problem but here are a couple of things that you could try:
`cd parallella/parallella-yoctobuild`
`source prepareyoctobuild.sh`
`bitbake -c cleansstate texinfo-dummy-native epiphany-elf-binutils-cross-epiphany`
`bitbake epiphany-elf-binutils-cross-epiphany`
You are likely to get the same error but it is always worth a try.. The idea of these commands is to clean out the recipe that provides makeinfo (texinfo-dummy-native) and to clean out the epiphany-elf-binutils-cross-epiphany recipe that has the problem.  Then bitbake just epiphany-elf-binutils-cross-epiphany will force a rebuild of texinfo-dummy-native and then epiphany-elf-binutils-cross-epiphany.

If you still have a problem .. Looking at the python in makeinfo at `build_parallella/tmp/sysroot/x86_64-linux/usr/bin/texinfo-dummy-native` I cant see exactly what is going wrong so your might like to add some python print statements to get more information about what arg[0], arg[1], this_binary and simple_binaries are to get a better idea about the failure.  To do this you could add print statements in makeinfo then rebuild the epiphany-elf-binutils-cross-epiphany recipe:
`bitbake -c cleansstate epiphany-elf-binutils-cross-epiphany`
`bitbake epiphany-elf-binutils-cross-epiphany`

I tried running the command `makeinfo --split-size=5000000 --split-size=5000000 --no-split -I/media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella/parallella-yoctobuild/build_parallella/tmp/work/x86_64-poky-linux-gnueabi/epiphany-elf-binutils-cross-epiphany/2.23-r0/git/etc -o standards.info /media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella/parallella-yoctobuild/build_parallella/tmp/work/x86_64-poky-linux-gnueabi/epiphany-elf-binutils-cross-epiphany/2.23-r0/git/etc/standards.texi` from a devshell but did not get any luck from that... The devshell creates an environment just the same as is created during the build so you get all the environment variables etc setup.. to do this run
`bitbake -c devshell epiphany-elf-binutils-cross-epiphany`

I also did a quick search for this problem with google but did not find anything obvious.

Let me know how you get on!

**Comment by sm0ketst** [comment]
Hi Peter!
Million Thanks for your cool work! It is really amazing and a big help to learn! 
I'll check during the weekend and I'll come back with feedback
JJ

**Comment by sm0ketst** [comment]
Hi Peter,

Weird, but binutils are apparently built after 2nd try...

What I did was to continue with:

```
 2076  source prepareyoctobuild.sh
 2077  bitbake -c cleansstate texinfo-dummy-native epiphany-elf-binutils-cross-epiphany
 2080  vim tmp/sysroots/x86_64-linux/usr/bin/texinfo-dummy-native/makeinfo 
++ print (sys.argv[1:]);
 2085  bitbake hdmi-image
```

devshell output:

```
| ['--split-size=5000000', '--split-size=5000000', '-I/media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/peteasa/parallella-yoctobuild/build_parallella/tmp/work/x86_64-poky-linux-gnueabi/epiphany-elf-binutils-cross-epiphany/2.23-r0/git/etc', '-o', 'configure.info', '/media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/peteasa/parallella-yoctobuild/build_parallella/tmp/work/x86_64-poky-linux-gnueabi/epiphany-elf-binutils-cross-epiphany/2.23-r0/git/etc/configure.texi']
```

It doesn't stop building now. Maybe DEPENDS/Order ??, 

Finally bb progressed until:

```
WARNING: Failed to fetch URL git://github.com/adapteva/epiphany-libs.git;branch=elink-redesign, attempting MIRRORS if available
ERROR: Fetcher failure: Unable to find revision bc94590302ce96e626c1f45e13746aa3b2b54946 in branch elink-redesign even from upstream
ERROR: Function failed: Fetcher failure for URL: 'git://github.com/adapteva/epiphany-libs.git;branch=elink-redesign'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella/parallella-yoctobuild/build_parallella/tmp/work/armv7ahf-vfp-neon-poky-linux-gnueabi/epiphany-sdk/1.0-r0/temp/log.do_fetch.11965
ERROR: Task 1489 (/media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella/parallella-yoctobuild/build_parallella/../meta-epiphany/recipes-epiphanysdk/epiphany-sdk/epiphany-sdk_1.0.bb, do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1571 tasks of which 654 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella/parallella-yoctobuild/build_parallella/../meta-epiphany/recipes-epiphanysdk/epiphany-sdk/epiphany-sdk_1.0.bb, do_fetch
```

I'm trying now again from a clean setup also checking why the fetch fails.

JJ

**Comment by sm0ketst** [comment]
It seems I get something different if I clone the 'parallela' vs the 'parallella-yoctobuild'

While using the 'parallella-yoctobuild' and after sourcing the 'initgitsubmodules.sh'

```
Switched to branch 'yoctobuild'
=================================
once only fetch done ready to run

   source prepareyoctobuild.sh

prepareyoctobuild.sh is sourced each
time you open a new shell
```

Then:

```
sm0ketst@neonbox:/media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella-yoctobuild/build_parallella$ bitbake hdmi-image
Parsing recipes: 100% |########################################################################################################################################################################################################################################| Time: 00:02:10
Parsing of 929 .bb files complete (0 cached, 929 parsed). 1332 targets, 69 skipped, 0 masked, 0 errors.
ERROR: No recipes available for:
  /media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella-yoctobuild/build_parallella/../meta-parallella/recipes-core/coreutils/coreutils_8.22.bbappend
  /media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella-yoctobuild/build_parallella/../meta-parallella/recipes-core/busybox/busybox_1.22.1.bbappend

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

```
sm0ketst@neonbox:/media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella-yoctobuild/build_parallella$ git branch -a
* elink-redesign
  remotes/origin/HEAD -> origin/elink-redesign
  remotes/origin/elink-redesign
  remotes/origin/parallella-elink-redesign
  remotes/origin/parallella-old-elink
  remotes/origin/yoctobuild
sm0ketst@neonbox:/media/sm0ketst/WDCWD10EAVS/data/devel/parallella.github/parallella-yoctobuild/build_parallella$ git remote -v
origin  git@github.com:peteasa/parallella-yoctobuild (fetch)
origin  git@github.com:peteasa/parallella-yoctobuild (push)
```

But if i clone the 'parallella' and then I move to 'parallela-yoctobuild' and I proceeed in the same way if dont see the last message from the 'initsubmodules.sh'

Launching the build now.

JJ

**Comment by sm0ketst** [comment]
Epiphany SDK fails to build because fetcher points to 'elink-redesign' and the branch is not longer there for any reason, so I tried:

```
SBRANCH = "2016.3"
SRCREV = "21b30b62641c37559f935e59a13c029d6b61f014"
```

Then I ended up in the 'coreutils/busybox' issue before.

Hints? 

JJ

**Comment by peteasa** [comment]
Ok so we are making progress.  Back to square one..  Yocto is very sensitive to how you build.  If for example you run bitbake then part way type `<Ctrl C> <Ctrl C>` then this will corrupt the cache and the best thing to do is start again from scratch because if the cache is corrupt it can be hard to recover.  I am not at my development machine right now but seems like your original problem was because the cache was corrupt in some way.  You fixed that for a couple of modules because you used -c cleansstate that cleans the cache for those modules.  Also if you do a build then try to update git or change the meta layers you will likely get the same effect with the cache messed up.

Best thing to do to recover is to start again from scratch but first look in the local.conf file in build_parallella/conf.  This file shows you where the cache is (default is build_parallella/sstate-cache) and where the download folder is (I think I moved this to parallella-yocobuild so that when you remove the build folder you dont necessarily delete all the downloaded files).  So to clean the cache and start again first start a new terminal window and navigate to the parallella-yoctobuild folder and type:
`rm -rf build_parallella`
Then check git and see if you are on the correct sha1 latest one is ef18ca8.  Then make sure that all the submodules are up to date
`git submodule foreach git fetch --all`
`git submodule update`
Should work and get all the submodules on the right sha1.  

Now you have found some renaming that has happened in epiphany-libs git.. look at the branch old-outdated-elink-redesign and see that  sha1 bc94590 is the required commit.  Line 35 of epiphany-sdk_1.0.inc (https://github.com/peteasa/meta-epiphany/blob/74778cf4d6355a27ed0a95fa6dc97590800b2573/recipes-epiphanysdk/epiphany-sdk/epiphany-sdk_1.0.inc#L35) has the branch spec ... change "elink-redesign" to "old-outdated-elink-redesign".  Now start again:
`source prepareyoctobuild.sh`
`bitbake hdmi-image`
In theory it should all work.  If not just try the bitbake again.. sometimes you are right there can be a build order dependancy that is messed up..  Look at https://github.com/peteasa/parallella-yoctobuild/wiki/Troubleshooting-notes#things-that-can-go-wrong-with-the-build where I listed commands that might help.  

If it all works let me know and perhaps create a push with the fix if you like.. Right now I am not able to update the script and test it.  When I get back I want to focus on getting the next version with the updated linux kernel and updated drivers etc running.

**Comment by sm0ketst** [comment]
Shit happens! :P 

I think I'm having the same issue with the dummy makeinfo.

```
--> assert arg[0] != '-' or arg[1] == '-' or 'E' not in arg or \
```

And in my case the script complains when parsing the -I. 

Same issue at [openbedded-core](http://lists.openembedded.org/pipermail/openembedded-core/2014-June/093459.html), the pathname contains '/OE/...' 

Mine contains /disk/WDCWD10EAVS/... life is so cruel!

Closed I think, thanks Peter!!! I'm building fine now. 
You have the PR with the new SBRANCH in the elink-redesign branch.

JJ
